"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['tagcounter.py']
DATA_FILES = ['data.db', 'aliases.yaml']
OPTIONS = {'includes': ['tagcounter.gui', 'tagcounter.counter', 'tagcounter.page', 'tagcounter.parser', 'tagcounter.logs']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    install_requires=['requests'],
    setup_requires=['py2app'],
)
